name: vinyl-tut
version: '0.1.0.0'
category: Web
author: Daniel Vianna
maintainer: dmlvianna <at> gmail <dot> com
copyright: MIT
license: BSD3
homepage: https://github.com/dmvianna/vinyl-tut#readme
extra-source-files:
- README.md
dependencies:
- base >=4.7 && <5
- vinyl
- lens
- doctest
- singletons
executables:
  vinyl-tut:
    main: Main.hs
    source-dirs: src
